id: IC3803960
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:12:28+00:00'
last_modified: '2022-06-07T17:53:27.103298+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21709
  title: གསོ་རིག་ཡིག་ཆ་ཉིང་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D7E2:
      image_group_id: I1KG21772
      title: ''
      total_pages: 356
      order: 1
      base_file: D7E2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
