id: P003144
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:43:18.103404
source_metadata:
  id: bdr:W1KG21709
  title: གསོ་རིག་ཡིག་ཆ་ཉིང་བསྡུས།
  author: ''
  volumes:
    bf4af9b6766b4d568dbbc0aac73f8bc9:
      image_group_id: I1KG21772
      title: ''
      volume_number: 1
      total_pages: 356
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
